AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-react-sample

  Sample SAM Template for lambda-react-sample

Resources:
  LambdaReactSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      Tracing: Active
      LoggingConfig:
        LogFormat: JSON
      PackageType: Image
      Architectures:
        - x86_64
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/lambda-react-sample:latest
      FunctionUrlConfig:
        AuthType: NONE
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./src

Outputs:
  LambdaReactSampleFunctionUrl:
    Description: "URL for the LambdaReactSample function"
    Value: !GetAtt LambdaReactSampleFunction.FunctionUrl
