AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-react-sample

  Sample SAM Template for lambda-react-sample

Resources:
  LambdaReactSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      PackageType: Image
      Architectures:
        - x86_64
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/lambda-react-sample:latest
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref LambdaReactSampleApi
        GetItemRoute:
          Type: Api
          Properties:
            Path: /api/items
            Method: GET
            RestApiId: !Ref LambdaReactSampleApi
        DynamicRoute:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
            RestApiId: !Ref LambdaReactSampleApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src

  LambdaReactSampleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: lambda-react-sample

Outputs:
  LambdaReactSampleApi:
    Description: "API Gateway endpoint URL without stage for LambdaReactSample function"
    Value: !Sub "https://${LambdaReactSampleApi}.execute-api.${AWS::Region}.amazonaws.com/lambda-react-sample"
